name: Test deployment

on:
  pull_request:
    branches: [main]

jobs:
  test-deploy:
    name: Test deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: yarn
      - name: yarn install
        run: yarn install --frozen-lockfile
      - name: download remote files
        run: yarn run remote-download
      - name: yarn build
        run: yarn build